# Generated by Django 5.2.9 on 2025-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
